/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Navigation as TechomahaNavigation
} from './components/navigation/navigation';

declare global {
  interface HTMLTechomahaNavigationElement extends TechomahaNavigation, HTMLElement {
  }
  var HTMLTechomahaNavigationElement: {
    prototype: HTMLTechomahaNavigationElement;
    new (): HTMLTechomahaNavigationElement;
  };
  interface HTMLElementTagNameMap {
    "techomaha-navigation": HTMLTechomahaNavigationElement;
  }
  interface ElementTagNameMap {
    "techomaha-navigation": HTMLTechomahaNavigationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "techomaha-navigation": JSXElements.TechomahaNavigationAttributes;
    }
  }
  namespace JSXElements {
    export interface TechomahaNavigationAttributes extends HTMLAttributes {
      
    }
  }
}

