/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import 'smart-image-wc';
import 'ionicons';


import {
  Input as TechomahaInput
} from './components/input/input';

declare global {
  interface HTMLTechomahaInputElement extends TechomahaInput, HTMLStencilElement {
  }
  var HTMLTechomahaInputElement: {
    prototype: HTMLTechomahaInputElement;
    new (): HTMLTechomahaInputElement;
  };
  interface HTMLElementTagNameMap {
    "techomaha-input": HTMLTechomahaInputElement;
  }
  interface ElementTagNameMap {
    "techomaha-input": HTMLTechomahaInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "techomaha-input": JSXElements.TechomahaInputAttributes;
    }
  }
  namespace JSXElements {
    export interface TechomahaInputAttributes extends HTMLAttributes {
      name?: string;
      placeholder?: string;
      type?: string;
      value?: string;
    }
  }
}


import {
  Theme as TechomahaTheme
} from './components/theme/theme';

declare global {
  interface HTMLTechomahaThemeElement extends TechomahaTheme, HTMLStencilElement {
  }
  var HTMLTechomahaThemeElement: {
    prototype: HTMLTechomahaThemeElement;
    new (): HTMLTechomahaThemeElement;
  };
  interface HTMLElementTagNameMap {
    "techomaha-theme": HTMLTechomahaThemeElement;
  }
  interface ElementTagNameMap {
    "techomaha-theme": HTMLTechomahaThemeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "techomaha-theme": JSXElements.TechomahaThemeAttributes;
    }
  }
  namespace JSXElements {
    export interface TechomahaThemeAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
