/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Button as TechomahaButton
} from './components/button/button';

declare global {
  interface HTMLTechomahaButtonElement extends TechomahaButton, HTMLElement {
  }
  var HTMLTechomahaButtonElement: {
    prototype: HTMLTechomahaButtonElement;
    new (): HTMLTechomahaButtonElement;
  };
  interface HTMLElementTagNameMap {
    "techomaha-button": HTMLTechomahaButtonElement;
  }
  interface ElementTagNameMap {
    "techomaha-button": HTMLTechomahaButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "techomaha-button": JSXElements.TechomahaButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface TechomahaButtonAttributes extends HTMLAttributes {
      
    }
  }
}

